### ISSUE TITLE
Discord app升级后新版本app-XXX子目录里没有version.dll导致无法启动

### ISSUE THREAD

**Issue by zeroxia** [aiqinxuancai/DiscordProxyStart#1]
比如原来app在这个子目录里：
app-1.0.9012

用 DiscordProxyStart 启动，会成功联网，但是Discord下载了新版本的app：
app-1.0.9013

此时Update.exe会立即启动这个新版本的app。这个目录里是肯定没有 version.dll 的，所以此时就无法联网了。

解决思路：

监控 Discord/ 下的 app-XXX 子目录。启动前记录状态，Process创建以后监控是否有新增 app-XXX 子目录，如果有新增，则杀掉 Process，再次复制 version.dll 到新增的子目录，然后再启动 Update.exe 。不过这里要确保版本更新完成后再杀掉进程，不知道这个状态如何可靠的获取。

**Comment by aiqinxuancai** [comment]
理论上关掉discord重新用DiscordProxyStart启动就行了

**Comment by zeroxia** [comment]
> 

好像不行。我看代码里也是找到第一个 app- 开头的子目录就返回了，所以有可能新版本的目录里还是没有拷贝到 version.dll 。
Discord 在成功联网启动后，才会删除旧版的 app-XXX 子目录。

**Comment by aiqinxuancai** [comment]
> > 
> 
> 
> 
> 好像不行。我看代码里也是找到第一个 app- 开头的子目录就返回了，所以有可能新版本的目录里还是没有拷贝到 version.dll 。
> 
> Discord 在成功联网启动后，才会删除旧版的 app-XXX 子目录。
> 
> 

好吧，我最近优化下

**Comment by LCAR979** [comment]
我今天就遇到了这个最新的情况，Discord目录下同时存在两个app-XXX目录，新版本目录下没有version.dll，启动失败。手动复制verson.dll到新目录之后，成功完成启动，旧版本目录自动删除。

**Comment by aiqinxuancai** [comment]
https://github.com/aiqinxuancai/DiscordProxyStart/releases/tag/v0.0.6
已经优化了代码，启动进程后等待更新窗口销毁才结束，期间会检查所有app-开头的目录并随时复制version.dll
