### ISSUE TITLE
The  Download File contains virus ?

### ISSUE THREAD

**Issue by hantsy** [aiqinxuancai/DiscordProxyStart#11]
My Antivirus prevents the download file: https://github.com/aiqinxuancai/DiscordProxyStart/releases/download/v0.0.12/DiscordProxyStart-win-amd64.zip

**Comment by aiqinxuancai** [comment]
由于使用了version.dll劫持，被误报为病毒我认为也可以理解，你可以考虑暂时关闭杀毒软件，或将其添加进白名单。
