### ISSUE TITLE
discord更新版本会导致程序异常

### ISSUE THREAD

**Issue by taozhiyu** [aiqinxuancai/DiscordProxyStart#12]
（没有截图）
大概就是占用了旧文件夹，

然后新打开的discord（update）不能正常使用，
全部关掉之后重新打开ProxyStart就好了。。。

**Comment by aiqinxuancai** [comment]
先用最新版本再试试

**Comment by taozhiyu** [comment]
下载的就是最新版，discord没更新无法测试，直接改discord的版本号也会报错。。。

**Comment by catshitz** [comment]
> 先用最新版本再试试

最新版必须“以管理员身份运行”才会触发自动删除旧版本来避免每次更新后的权限问题报错框无法打开，可是DiscordProxyStart.exe本身默认是以非管理员身份运行的，所以目前最新版还是没有全自动化无痕化的解决更新报错的问题，可能还得更新加一项让可执行文件默认以管理员身份运行，那样基本没啥问题了。

**Comment by aiqinxuancai** [comment]
https://github.com/aiqinxuancai/DiscordProxyStart/releases/tag/v0.0.13-beta.1
试试看这个

**Comment by taozhiyu** [comment]
Solved
