### ISSUE TITLE
没有找到Discord閌装目录#1

### ISSUE THREAD

**Issue by Ekzar** [aiqinxuancai/DiscordProxyStart#14]
Hi.
Windows 11 23H2
I followed the instructions, but when I launch it I get the following error:
没有找到Discord閌装目录#1
![image](https://github.com/user-attachments/assets/64daa837-d6de-4bee-9c75-8851a0f357c2)
Discord installation path: C:\Users\ekzar\AppData\Local\Discord
What am I doing wrong?

**Comment by aiqinxuancai** [comment]
如果你是从Discord的官方网站下载并安装，理论上是不会出现此问题的，此错误表示无法从注册表中找到Discord的安装信息，你可以尝试在配置文件中指定Discord的安装目录，像是这样：
```ini
[Config]
Proxy=http://127.0.0.1:1080
Path=C:\Users\ekzar\AppData\Local\Discord
```

**Comment by Ekzar** [comment]
我从官方网站安装了Discord。
该问题被认为是由于操作系统的区域设置造成的。
您的解决方案解决了问题。
谢谢你！
