### ISSUE TITLE
日志创建问题

### ISSUE THREAD

**Issue by xmbhjQAQ** [aiqinxuancai/DiscordProxyStart#15]
当我通过桌面快捷方式启动 DiscordProxyStart.exe 时，日志文件会在桌面上创建。而直接从文件位置启动时，日志文件会在该文件位置下创建。

**Comment by aiqinxuancai** [comment]
这取决于你的快捷方式的这里，通常如果是右键exe发送到桌面快捷方式，则当前目录会设置为exe所在目录。
![image](https://github.com/user-attachments/assets/9348c252-644d-4e90-948c-d1baf430ec3c)
---
除非你的桌面上放的不是快捷方式，而直接是exe文件
