### ISSUE TITLE
请问cfw的话应该如何填写Proxy

### ISSUE THREAD

**Issue by prajna0** [aiqinxuancai/DiscordProxyStart#2]
非常感谢作者提供这么好的Disocrd代理解决方案，感谢无私奉献

**Comment by aiqinxuancai** [comment]
不清楚，我没有使用过，一般代理工具都会有本地开放http或socks端口的设置选项，你可以找一下看看。

如果是设置中仅显示了端口(如1080)，http代理应为 `http://127.0.0.1:1080`
