### ISSUE TITLE
为什么你发布的exe只有4M多，我发布后却有十几M呢？哪里不对吗？

### ISSUE THREAD

**Issue by Levyrii** [aiqinxuancai/DiscordProxyStart#6]
![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/11383609/a37624cb-de31-4351-8087-4540f0450695)

**Comment by aiqinxuancai** [comment]
[建议查看编译脚本哦](https://github.com/aiqinxuancai/DiscordProxyStart/blob/master/.github/workflows/dotnet-core-desktop.yml)

**Comment by Levyrii** [comment]
明白了，谢谢回复！
