### ISSUE TITLE
添加对不和谐金丝雀的支持?

### ISSUE THREAD

**Issue by 00a1** [aiqinxuancai/DiscordProxyStart#7]
是否可以添加对不和谐金丝雀的支持?

**Comment by aiqinxuancai** [comment]
我这里测试[discord canary](https://canary.discord.com/)是可以正常启动的。

**Comment by aiqinxuancai** [comment]
https://github.com/aiqinxuancai/DiscordProxyStart/releases/tag/v0.0.8
我在v0.0.8中增加了Conifg.ini中Path的设置项，正如你上面的图上的使用方法，你可以试一下。

**Comment by Reckless144** [comment]
> 我添加了新版本的路径并运行它，但它没有添加文件，而且它也打开了正常的不和谐而不是金丝雀 ![Screenshot_4](https://private-user-images.githubusercontent.com/50469859/287610654-9f0448c4-8324-44c6-a008-3d078f22ba7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTQxODgsIm5iZiI6MTcwMzM1Mzg4OCwicGF0aCI6Ii81MDQ2OTg1OS8yODc2MTA2NTQtOWYwNDQ4YzQtODMyNC00NGM2LWEwMDgtM2QwNzhmMjJiYTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE3NTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YjZlM2UzOTliZmRhNjFmYzM1MDI0OTg0ZTYzNWM4NGQ5YTYzODNlNTU5YTYwMTY2M2Q1NTUzMDE1ZTA4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQ6-mKdARnnSSLiO3oiybPrQTwTkJhKufTDwyR7dKdE)

myabe is you download two discord,and this exe file first find the common one ,you can try uninstall the common one and only left the canary version discord ,then run this exe file again

**Comment by shinyashen** [comment]
> https://github.com/aiqinxuancai/DiscordProxyStart/releases/tag/v0.0.8 我在v0.0.8中增加了Conifg.ini中Path的设置项，正如你上面的图上的使用方法，你可以试一下。

新增的Path设置项似乎并没有生效。
![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/90324553/1712c6a1-efaa-4d1f-9137-93c765035908)

并且，如果在Conifg.ini中调换Path与Proxy设置项的位置，会导致程序无法读取Proxy配置而报错退出。
![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/90324553/98b478b6-b935-4f70-9e22-66f2d12d2ef5)

![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/90324553/6444a0af-5902-4ef0-8ec1-8ada72c43b1b)

**Comment by shinyashen** [comment]
> > > https://github.com/aiqinxuancai/DiscordProxyStart/releases/tag/v0.0.8 我在v0.0.8中增加了Conifg.ini中Path的设置项，正如你上面的图上的使用方法，你可以试一下。
> > 
> > 
> > 新增的Path设置项似乎并没有生效。 ![image](https://private-user-images.githubusercontent.com/90324553/325073480-1712c6a1-efaa-4d1f-9137-93c765035908.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzM1MzUsIm5iZiI6MTcxMzkzMzIzNSwicGF0aCI6Ii85MDMyNDU1My8zMjUwNzM0ODAtMTcxMmM2YTEtZWZhYS00ZDFmLTkxMzctOTNjNzY1MDM1OTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzllYzk2ODdmYzVkOTAwOTVhNGYxY2JkN2MyOTIyMjkxMDY0YWI3MTE0Y2M3ZmExNWNmNTc2MDg5YWUxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhPX9yQC6x9lOWJhNXCMlL_eCKN-xhvUaGAAIvlZyPM)
> > 并且，如果在Conifg.ini中调换Path与Proxy设置项的位置，会导致程序无法读取Proxy配置而报错退出。 ![image](https://private-user-images.githubusercontent.com/90324553/325073404-98b478b6-b935-4f70-9e22-66f2d12d2ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzM1MzUsIm5iZiI6MTcxMzkzMzIzNSwicGF0aCI6Ii85MDMyNDU1My8zMjUwNzM0MDQtOThiNDc4YjYtYjkzNS00ZjcwLTllMjItNjZmMmQxMmQyZWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZTMyMmYzYzliY2UwYzdlZDg3ZDgyYmRjZTY0NjRkOTZmY2M4ZDhkNjdhNmEwNWZjMjAxNDc1NDhiZDVmNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._UBvG6n9JFAHru3ka0cQpqH8z4hHiagUzCFBsn7a06Q)
> > ![image](https://private-user-images.githubusercontent.com/90324553/325073351-6444a0af-5902-4ef0-8ec1-8ada72c43b1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzM1MzUsIm5iZiI6MTcxMzkzMzIzNSwicGF0aCI6Ii85MDMyNDU1My8zMjUwNzMzNTEtNjQ0NGEwYWYtNTkwMi00ZWYwLThlYzEtOGFkYTcyYzQzYjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNGZhODg3NGE1YzA1NzIyYmMzMjI0NGI1MGIwMzIwZjAyOGJlM2QxNmM0YTYyN2FjZTZmNGY5ZDg4YTZhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH9mnqvBWQeEoXxucfzUYxdamKuTeD3IkscBp8Wi3ws)
> 
> 试一下0.0.10吧，目录设置到Update.exe的那一级

调换位置后报错的问题已经修复，但仍然无法读取Path设置项(应为所设置的1.0.9042版本)。
![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/90324553/c6104397-4da5-428d-835f-f00e8599e430)

![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/90324553/e6b88c11-8628-4945-a948-799b454c8d2f)

**Comment by aiqinxuancai** [comment]
> 目录设置到Update.exe的那一级


> > > > https://github.com/aiqinxuancai/DiscordProxyStart/releases/tag/v0.0.8 我在v0.0.8中增加了Conifg.ini中Path的设置项，正如你上面的图上的使用方法，你可以试一下。
> > > 
> > > 
> > > 新增的Path设置项似乎并没有生效。 ![image](https://private-user-images.githubusercontent.com/90324553/325073480-1712c6a1-efaa-4d1f-9137-93c765035908.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzM1MzUsIm5iZiI6MTcxMzkzMzIzNSwicGF0aCI6Ii85MDMyNDU1My8zMjUwNzM0ODAtMTcxMmM2YTEtZWZhYS00ZDFmLTkxMzctOTNjNzY1MDM1OTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNzllYzk2ODdmYzVkOTAwOTVhNGYxY2JkN2MyOTIyMjkxMDY0YWI3MTE0Y2M3ZmExNWNmNTc2MDg5YWUxZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MhPX9yQC6x9lOWJhNXCMlL_eCKN-xhvUaGAAIvlZyPM)
> > > 并且，如果在Conifg.ini中调换Path与Proxy设置项的位置，会导致程序无法读取Proxy配置而报错退出。 ![image](https://private-user-images.githubusercontent.com/90324553/325073404-98b478b6-b935-4f70-9e22-66f2d12d2ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzM1MzUsIm5iZiI6MTcxMzkzMzIzNSwicGF0aCI6Ii85MDMyNDU1My8zMjUwNzM0MDQtOThiNDc4YjYtYjkzNS00ZjcwLTllMjItNjZmMmQxMmQyZWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZTMyMmYzYzliY2UwYzdlZDg3ZDgyYmRjZTY0NjRkOTZmY2M4ZDhkNjdhNmEwNWZjMjAxNDc1NDhiZDVmNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._UBvG6n9JFAHru3ka0cQpqH8z4hHiagUzCFBsn7a06Q)
> > > ![image](https://private-user-images.githubusercontent.com/90324553/325073351-6444a0af-5902-4ef0-8ec1-8ada72c43b1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzM1MzUsIm5iZiI6MTcxMzkzMzIzNSwicGF0aCI6Ii85MDMyNDU1My8zMjUwNzMzNTEtNjQ0NGEwYWYtNTkwMi00ZWYwLThlYzEtOGFkYTcyYzQzYjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA0MzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNGZhODg3NGE1YzA1NzIyYmMzMjI0NGI1MGIwMzIwZjAyOGJlM2QxNmM0YTYyN2FjZTZmNGY5ZDg4YTZhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SH9mnqvBWQeEoXxucfzUYxdamKuTeD3IkscBp8Wi3ws)
> > 
> > 
> > 试一下0.0.10吧，目录设置到Update.exe的那一级
> 
> 调换位置后报错的问题已经修复，但仍然无法读取Path设置项(应为所设置的1.0.9042版本)。 ![image](https://private-user-images.githubusercontent.com/90324553/325093219-c6104397-4da5-428d-835f-f00e8599e430.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mzc1OTIsIm5iZiI6MTcxMzkzNzI5MiwicGF0aCI6Ii85MDMyNDU1My8zMjUwOTMyMTktYzYxMDQzOTctNGRhNS00MjhkLTgzNWYtZjAwZTg1OTllNDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1NDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4Nzc4MDdkZjczMmVmYTQxOTIwMWIyOGJjZjM5MDg4YWQ1YmMwMTU5ZWFjNTQ0YjE2MzgxYzY5YWYwMmQxYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8KI418TExcZ5Uy4kfeKsX9-6zhBJ7mIyz3KITw8FeM)
> 
> ![image](https://private-user-images.githubusercontent.com/90324553/325093255-e6b88c11-8628-4945-a948-799b454c8d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mzc1OTIsIm5iZiI6MTcxMzkzNzI5MiwicGF0aCI6Ii85MDMyNDU1My8zMjUwOTMyNTUtZTZiODhjMTEtODYyOC00OTQ1LWE5NDgtNzk5YjQ1NGM4ZDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1NDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMmQ4ODcwNTU0Yzk5NGI2Y2M0NGNkZTViMGQ0OTAyMjE0MzIzODg2OWJkYWE5MzYwOTJiNDNlNTVjMGZkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wV5kvQ7GI6Jf9-bgn4TXJtvWLqs-VVJNEewX-cYoVcU)

目录应该是这个，另外重新下一下0.0.10 https://github.com/aiqinxuancai/DiscordProxyStart/releases/download/untagged-a06340c2509644d17a84/DiscordProxyStart-win-amd64.zip

![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/4475018/78a42f50-673e-4690-845a-8d9c726c9ae8)
