### ISSUE TITLE
0.10版本普通版更新过程中可能会出错

### ISSUE THREAD

**Issue by tokimango** [aiqinxuancai/DiscordProxyStart#8]
非金丝雀版本，更新过程中旧版app文件夹没有找到Discord.exe，会导致在旧版app文件夹下寻找DicordCanary.exe文件。导致报错cannot access

**Comment by Blood3C** [comment]
我Discord也是正式版，ProxyStart更新到0.10版本 启动提示找不到DiscordCanary.exe
然后我去dc安装目录把主程序文件名Discord.exe改成DiscordCanary.exe就可以正常启动了
期待开发者更新优化
