### ISSUE TITLE
更新版本后无法启动，提示访问Discord被拒

### ISSUE THREAD

**Issue by c6n1aa** [aiqinxuancai/DiscordProxyStart#9]
![image](https://github.com/aiqinxuancai/DiscordProxyStart/assets/45552513/13468094-ada0-4313-a162-016b98d4146c)
更新v0.0.11后启动提示这个了，使用管理员启动也是一样的提示
配置文件里只配置了代理地址

**Comment by c6n1aa** [comment]
删除discord旧版本后解决了

**Comment by aiqinxuancai** [comment]
> 这个确实蛋疼，每次只要更新都得手动删一遍旧档

使用最新release即可
